version: "3.8"
services:
  mongodb:
    container_name: mongo_producao
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - producao-net


  producao_service:
    build: .
    container_name: producao
    restart: always
    ports:
      - 8080:8080
    networks:
      - producao-net
    depends_on:
      - mongodb
    environment:
      DB_URL: mongodb
    working_dir: /usr/src/producao
    command: /usr/src/producao/app-startup.sh

networks:
  producao-net:
    driver: bridge